- name: Copy CentOS Base Source To CentOS/RedHat
  copy: src=CentOS-Base-{{ ansible_distribution_major_version }}.repo dest=/etc/yum.repos.d/CentOS-Base-{{ ansible_distribution_major_version }}.repo
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Copy CentOS Epel Source To CentOS/RedHat
  copy: src=CentOS-epel.repo dest=/etc/yum.repos.d/CentOS-epel.repo
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Copy Selinux To CentOS/RedHat
  copy: src=selinux dest=/etc/selinux/config  owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Copy Yum Group Script To CentOS/RedHat
  copy: src=Development.sh dest={{ code_src_dir }}/Development.sh owner=root group=root mode=0755
