- name: Install Development Tools software
  shell: /bin/bash {{ code_src_dir }}/Development.sh
  ignore_errors: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Install Chrony Software
  yum: name=chrony state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Chrony Time Server
  shell: echo "server {{ time_servers }}" >> /etc/chrony.conf
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Start Chronyd Service
  service: name=chronyd enabled=true state=started
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
- name: Firewalld Or Useless Services Disable For CentOS/RHEL7
  shell: systemctl disable NetworkManager.service NetworkManager-dispatcher.service firewalld.service
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
- name: Firewalld Or Useless Services Disable For CentOS/RHEL6
  shell: for LONG in `chkconfig --list|grep "3:on"|awk '{print $1}'|grep -vE "crond|network|sshd|rsyslog"`;do chkconfig $LONG off;done
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
