- name: Backup Original YUM Source
  shell: mkdir /etc/yum.repos.d/backup && mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup
  when: ansible_os_family == "RedHat"
- name: Copy CentOS Base Source To CentOS/RedHat
  template: src=CentOS-Base-{{ ansible_distribution_major_version }}.repo dest=/etc/yum.repos.d/CentOS-Base-{{ ansible_distribution_major_version }}.repo
  when: ansible_os_family == "RedHat"
- name: Copy CentOS Epel Source To CentOS/RedHat
  template: src=CentOS-epel.repo dest=/etc/yum.repos.d/CentOS-epel.repo
  when: ansible_os_family == "RedHat"
- name: Copy Selinux To CentOS/RedHat
  copy: src=selinux dest=/etc/selinux/config  owner=root group=root mode=0644
  when: ansible_os_family == "RedHat"
- name: Copy Yum Group Script To CentOS/RedHat
  copy: src=Development.sh dest={{ code_path }}/Development.sh owner=root group=root mode=0755
