  - name: restart mysql
    service: name=mysql state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  - name: restart mariadb
    service: name=mariadb state=restarted
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
