  - name: Stop Httpd Service In RedHat Client For 6
    shell: /etc/init.d/httpd stop
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  - name: Stop Httpd Service In RedHat Client For 7
    shell: systemctl stop httpd
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  - name: Delete Boot Start In RedHat Client For 6
    shell: chkconfig --del httpd
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  - name: Delete Boot Start In RedHat Client For 7
    shell: systemctl disable httpd
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  - name: Delete Apache Dir In RedHat Client
    shell: rm -rf {{ soft_install_dir }}/httpd-{{ apache_version }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Apache Service Script In RedHat Client For 6
    shell: rm -rf /etc/init.d/httpd
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  - name: Delete Apache Service Script In RedHat Client For 6
    shell: rm -rf /usr/lib/systemd/system/httpd.service && systemctl daemon-reload
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  - name: Delete Apache User
    shell: userdel {{ apache_user }}
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
