- name: Delete Apr Or Apr-util Software In Redhat Client
  shell: rm -rf {{ soft_install_dir }}/apr {{ soft_install_dir }}/apr-util {{ soft_install_dir }}/apr-{{ apr_version }} {{ soft_install_dir }}/apr-util-{{ apr_util_version }}
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
