  - name: Copy Pcre Software To Redhat Client
    copy: src=pcre-{{ pcre_version }}.tar.gz dest={{ code_path }}/pcre-{{ pcre_version }}.tar.gz owner=root group=root
    when: ansible_os_family == "RedHat"
