  - name: Delete Apache compression Software In Redhat Client
    shell: rm -rf code_path/httpd-{{ httpd_version }} {{ code_path }}/libiconv-{{ libiconv_version }}
    ignore_errors: yes
    when: ansible_os_family == "RedHat"
