- name: Install MySQL Software Depend In Redhat Client For 6
  yum: name={{item}} state=present
  with_items:
    - cmake
    - gcc
    - gcc-c++
    - ncurses-devel
    - bison
    - zlib
    - libxml++
    - openssl
    - openssl-devel
    - ncurses-devel
    - autoconf
    - numactl
  ignore_errors: True
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
- name: Install MySQL Software Depend In Redhat Client For 7
  yum: name={{item}} state=present
  with_items:
    - cmake
    - gcc
    - gcc-c++
    - ncurses-devel
    - bison
    - zlib
    - libxml2
    - openssl
    - openssl-devel
    - ncurses-devel
    - autoconf
    - numactl
  ignore_errors: True
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
