galaxy_info:
  author: Liu Long
  description: Install initializtion Software
  license: MIT
  min_ansible_version: 2.5.2
  platforms:
  - name: CentOS
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
dependencies: []
